
THEOS_DEVICE_IP = 130.64.136.194

include theos/makefiles/common.mk
ARCHS = armv6
TARGET = iphone:6.1

TWEAK_NAME = sentry_tweak

sentry_tweak_FILES = Tweak.xm

include $(THEOS_MAKE_PATH)/tweak.mk


